### ISSUE TITLE
F673AV9也解压失败，提供原文件供大神

### ISSUE THREAD

**Issue by wangzhu83** [TommyLau/ztecfg#2]
Device name: F673AV9

Traceback (most recent call last):
  File "ztecfg.py", line 265, in <module>
  File "ztecfg.py", line 256, in main
  File "ztecfg.py", line 104, in unpack
  File "construct\core.py", line 288, in parse
  File "construct\core.py", line 300, in parse_stream
  File "construct\core.py", line 312, in _parsereport
  File "construct\core.py", line 1981, in _parse
  File "construct\core.py", line 312, in _parsereport
  File "construct\core.py", line 2439, in _parse
  File "construct\core.py", line 312, in _parsereport
  File "construct\core.py", line 841, in _parse
  File "construct\core.py", line 92, in stream_read
construct.core.StreamError: Error in path (parsing) -> content
stream read less than specified amount, expected 31296, found 24357
[7744] Failed to execute script ztecfg
[ctce8_F673AV9.zip](https://github.com/TommyLau/ztecfg/files/5261651/ctce8_F673AV9.zip)

**Comment by yuleniwo** [comment]
> Device name: F673AV9
> 
> Traceback (most recent call last):
> File "ztecfg.py", line 265, in 
> File "ztecfg.py", line 256, in main
> File "ztecfg.py", line 104, in unpack
> File "construct\core.py", line 288, in parse
> File "construct\core.py", line 300, in parse_stream
> File "construct\core.py", line 312, in _parsereport
> File "construct\core.py", line 1981, in _parse
> File "construct\core.py", line 312, in _parsereport
> File "construct\core.py", line 2439, in _parse
> File "construct\core.py", line 312, in _parsereport
> File "construct\core.py", line 841, in _parse
> File "construct\core.py", line 92, in stream_read
> construct.core.StreamError: Error in path (parsing) -> content
> stream read less than specified amount, expected 31296, found 24357
> [7744] Failed to execute script ztecfg
> [ctce8_F673AV9.zip](https://github.com/TommyLau/ztecfg/files/5261651/ctce8_F673AV9.zip)

怀疑你备份的文件有问题，文件的大小偏小，试试看看能不能用备份的文件还原回去。

**Comment by polarstars** [comment]
你好，我备份的673AV9也遇到错误
Zlib.error: Error -3 While decompressing data: incorrect header check
附件里是 备份的文件
[ctce8_F673AV9.zip](https://github.com/TommyLau/ztecfg/files/5859750/ctce8_F673AV9.zip)

**Comment by TommyLau** [comment]
应该是不同的备份方式了，之前的应该是 zlib，这个应该不是。
