### ISSUE TITLE
请求支持F653GV9光猫

### ISSUE THREAD

**Issue by battenmufang** [TommyLau/ztecfg#7]
报错代码：
Device name: F653GV9eg

Block 1: size=32134, compressed=32144, offset=0
Traceback (most recent call last):
  File "ztecfg.py", line 265, in <module>
  File "ztecfg.py", line 256, in main
  File "ztecfg.py", line 114, in unpack
zlib.error: Error -3 while decompressing data: incorrect header check
[24836] Failed to execute script ztecfg

**Comment by battenmufang** [comment]
报错在标头检查时不正确，但是这个文件是正常从光猫CMCCAdmin用户下备份出来的
